[theme]
primaryColor = "#0056b3"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f6f9"
textColor = "#2c3e50"
font = "sans serif"

[server]
toolbarMode = "minimal"
headless = true

[client]
# Essa linha mágica desliga aquele menu feio automático do Streamlit
showSidebarNavigation = false
